apiVersion: v1
kind: ConfigMap
metadata:
  namespace: "{{ .Namespace }}"
  name: "{{ .Name }}"
data:
  {{ .SnitchConfigName }}: |
    dc={{ .DatacenterName }}
    rack={{ .RackName }}
    prefer_local=false
